# This is a file for you to write an un-named mutation. 
# Only one un-named mutation is allowed per file.
mutation {
  movieMetadata_insert(
    data: {id: "11111111222233334444555555555555", movieId: "11111111222233334444555555555555", description: "A warm and inviting christmas movie about a man who will do whatever it takes to re-unite with a lost love", rating: 5, releaseYear: 1988}
  )
}